-- MySQL Script generated by MySQL Workbench
-- Mon Aug 21 11:01:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RTSystems
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RTSystems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RTSystems` DEFAULT CHARACTER SET utf8 ;
USE `RTSystems` ;

-- -----------------------------------------------------
-- Table `RTSystems`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RTSystems`.`supplier` (
  `supplierID` INT NOT NULL,
  `supplierCodigo` VARCHAR(50) NULL,
  `supplierName` VARCHAR(80) NULL,
  `supplierContato` VARCHAR(14) NULL,
  `supplierEmail` VARCHAR(45) NULL,
  `supplierEndereco` VARCHAR(100) NULL,
  `supplierDoc` VARCHAR(14) NULL,
  `supplierCustos` FLOAT NULL,
  PRIMARY KEY (`supplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RTSystems`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RTSystems`.`product` (
  `productID` INT NOT NULL,
  `productCodigo` VARCHAR(50) NULL,
  `productName` VARCHAR(80) NULL,
  `productDescricao` VARCHAR(100) NULL,
  `productValor` FLOAT NULL,
  `productQtde` INT NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RTSystems`.`supplier_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RTSystems`.`supplier_has_product` (
  `supplier_supplierID` INT NOT NULL,
  `product_productID` INT NOT NULL,
  PRIMARY KEY (`supplier_supplierID`, `product_productID`),
  INDEX `fk_supplier_has_product_product1_idx` (`product_productID` ASC) VISIBLE,
  INDEX `fk_supplier_has_product_supplier1_idx` (`supplier_supplierID` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_has_product_supplier1`
    FOREIGN KEY (`supplier_supplierID`)
    REFERENCES `RTSystems`.`supplier` (`supplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_product_product1`
    FOREIGN KEY (`product_productID`)
    REFERENCES `RTSystems`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `rtsystems`.`users` (
  `usersID` INT NOT NULL AUTO_INCREMENT,
  `usersNome` VARCHAR(45) NOT NULL,
  `usersPswd` VARCHAR(45) NOT NULL,
  `usersPermissao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usersID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



create table users(userNome VARCHAR(80) NOT NULL, permissao VARCHAR(1));
insert into users values(null, "Adm", "@Adm", 1);
select * from users;



INSERT INTO supplier VALUES(null, "1234567B", "Rhyan Lucca", "11912345678", "chicosbar@gmail.com", "Rua Belem 68 ap 13", "51067792864", NULL);
INSERT INTO supplier VALUES(null, "1234567A", "Rodrigo´s Bar", "11987654311", "Rodrigos@gmail.com", "Rua Belem 68 ap 13", "51067792864", NULL);
INSERT INTO supplier VALUES(null, "1234567C", "Papariko´s Bar", "11945678792", "paparikos@gmail.com", "Rua Belem 68 ap 13", "51067792864", NULL);
INSERT INTO supplier VALUES(null, "1234567D", "Cabeçuda´s Bar", "11956780988", "cabecudas@gmail.com", "Rua Belem 68 ap 13", "51067792864", NULL);
