-- MySQL Script generated by MySQL Workbench
-- Mon Aug 14 17:05:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RTSystems
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RTSystems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RTSystems` DEFAULT CHARACTER SET utf8 ;
USE `RTSystems` ;

-- -----------------------------------------------------
-- Table `RTSystems`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RTSystems`.`fornecedores` (
  `idFornecedores` INT NOT NULL AUTO_INCREMENT,
  `codigoFornecedores` VARCHAR(50) NULL,
  `nomeFornecedores` VARCHAR(100) NOT NULL,
  `contatoFornecedores` VARCHAR(11) NOT NULL,
  `emailFornecedores` VARCHAR(50) NULL DEFAULT NULL,
  `enderecoFornecedores` VARCHAR(100) NULL,
  PRIMARY KEY (`idFornecedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RTSystems`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RTSystems`.`produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `nomeProdutos` VARCHAR(45) NOT NULL,
  `descricaoProdutos` VARCHAR(45) NULL DEFAULT NULL,
  `valorProdutos` FLOAT NOT NULL,
  `qtdeProdutos` INT NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RTSystems`.`fornecedores_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RTSystems`.`fornecedores_has_produtos` (
  `fornecedores_codigoFornecedores` INT NOT NULL,
  `produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`fornecedores_codigoFornecedores`, `produtos_idProdutos`),
  INDEX `fk_fornecedores_has_produtos_produtos1_idx` (`produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_fornecedores_has_produtos_fornecedores_idx` (`fornecedores_codigoFornecedores` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedores_has_produtos_fornecedores`
    FOREIGN KEY (`fornecedores_codigoFornecedores`)
    REFERENCES `RTSystems`.`fornecedores` (`idFornecedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedores_has_produtos_produtos1`
    FOREIGN KEY (`produtos_idProdutos`)
    REFERENCES `RTSystems`.`produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO fornecedores VALUES(null, "1234567B", "Rhyan Lucca", "11912345678", "chicosbar@gmail.com", "Rua Belem 68 ap 13");
INSERT INTO fornecedores VALUES(null, "1234567A", "Rodrigo´s Bar", "11987654311", "Rodrigos@gmail.com", "Rua Belem 68 ap 13");
INSERT INTO fornecedores VALUES(null, "1234567C", "Papariko´s Bar", "11945678792", "paparikos@gmail.com", "Rua Belem 68 ap 13");
INSERT INTO fornecedores VALUES(null, "1234567D", "Cabeçuda´s Bar", "11956780988", "cabecudas@gmail.com", "Rua Belem 68 ap 13");

#DELETE FROM fornecedores WHERE idFornecedores = I009;

select * from fornecedores;

